// =============================================================================
// Resources/EnStrings.cs
//
// SINOSSI: Traduzione inglese di ItStrings.Map — Fase 2 dell'internazionalizzazione.
//   Stesse chiavi esatte di ItStrings (stesso ordine/stessi commenti di
//   raggruppamento, per facilitare il confronto riga per riga), stesso numero
//   e ordine di segnaposto {0},{1},... nelle stringhe con string.Format.
//   Selezionato da Strings.SetLanguage("en") — vedi Strings.cs.
// =============================================================================

using System.Collections.Generic;

namespace StradarioApp.Resources
{
    internal static class EnStrings
    {
        public static readonly Dictionary<string, string> Map = new()
        {
            // Services/PoiSearchService.cs — POI category combo labels
            // (built-in, see Categories/AllCategories/LocalizedCategoryLabel
            // in ItStrings.cs for the key convention). User-added custom
            // categories are not translated here — see the note there.
            ["PoiCategory___special___address"] = "Search an address",
            ["PoiCategory___special___city"] = "Search a city (partial name OK)",
            ["PoiCategory_railway_station"] = "railway stations",
            ["PoiCategory_station_subway"] = "subway stations",
            ["PoiCategory_amenity_pharmacy"] = "pharmacies",
            ["PoiCategory_amenity_restaurant"] = "restaurants",
            ["PoiCategory_amenity_bar"] = "bars",
            ["PoiCategory_amenity_cafe"] = "cafes",
            ["PoiCategory_amenity_parking"] = "parking",
            ["PoiCategory_amenity_hospital"] = "hospitals",
            ["PoiCategory_amenity_school"] = "schools",
            ["PoiCategory_tourism_hotel"] = "hotels",
            ["PoiCategory_shop_supermarket"] = "supermarkets",
            ["PoiCategory_shop_butcher"] = "butchers",
            ["PoiCategory_shop_bakery"] = "bakeries",
            ["PoiCategory_amenity_bank"] = "banks",
            ["PoiCategory_amenity_atm"] = "ATMs",
            ["PoiCategory_amenity_place_of_worship"] = "places of worship",
            ["PoiCategory_tourism_museum"] = "museums",
            ["PoiCategory_aeroway_aerodrome"] = "airports",
            ["PoiCategory_highway_bus_stop"] = "bus stops",
            ["PoiCategory_amenity_toilets"] = "restrooms",
            ["PoiCategory_amenity_fuel"] = "gas stations",
            ["PoiCategory_amenity_post_office"] = "post offices",
            ["PoiCategory_amenity_library"] = "libraries",
            ["PoiCategory_amenity_cinema"] = "cinemas",
            ["PoiCategory_amenity_vending_machine"] = "vending machines",
            ["PoiCategory_shop_newsagent"] = "newsstands",
            ["PoiCategory_amenity_fast_food"] = "fast food",
            ["PoiCategory_shop_tobacco"] = "tobacco shops",
            ["PoiCategory_shop_hairdresser"] = "hairdressers",
            ["PoiCategory_amenity_veterinary"] = "veterinarians",
            ["PoiCategory_amenity_charging_station"] = "EV charging stations",
            ["PoiCategory_amenity_drinking_water"] = "drinking fountains",
            ["PoiCategory_shop_laundry"] = "laundromats",
            ["PoiCategory_amenity_taxi"] = "taxi stands",
            ["PoiCategory_amenity_bus_station"] = "bus terminals",
            ["PoiCategory_aeroway_terminal"] = "airport terminals",
            ["PoiCategory_tourism_attraction"] = "tourist attractions",
            ["PoiCategory_tourism_viewpoint"] = "viewpoints",
            ["PoiCategory_historic_monument"] = "monuments",
            ["PoiCategory_amenity_bicycle_rental"] = "bike rental",
            ["PoiCategory_amenity_bicycle_parking"] = "bike parking",
            ["PoiCategory_tourism_information"] = "tourist information offices",
            ["PoiCategory_amenity_bureau_de_change"] = "currency exchange offices",

            // Services/PoiSearchService.cs (righe di log passate a onProgress,
            // mostrate in UI/PoiSearchLogWindow)
            ["PoiSearchService_AttendoNominatim"] = "Waiting for a turn to query Nominatim (max 1 request/second)...",
            ["PoiSearchService_InterrogoNominatimLuogo"] = "Querying Nominatim for the place \"{0}\"...",
            ["PoiSearchService_NominatimNessunLuogo"] = "Nominatim found no place for \"{0}\".",
            ["PoiSearchService_InterrogoNominatimIndirizzo"] = "Querying Nominatim for the address \"{0}\"...",
            ["PoiSearchService_IndirizziTrovati"] = "Found {0} matching addresses.",
            ["PoiSearchService_TrovataInCache"] = "Found the same search ({0}={1}) for this area in cache: no new request to Overpass.",
            ["PoiSearchService_QueryOverpassCostruita"] = "Built the Overpass query for \"{0}={1}\" in the area {2},{3} – {4},{5}.",
            ["PoiSearchService_InvioRichiestaOverpass"] = "Sending the request to the public Overpass server (overpass-api.de)...",
            ["PoiSearchService_RispostaOverpassRicevuta"] = "Response received from Overpass, analyzing the elements found...",
            ["PoiSearchService_ElementiValidiTrovati"] = "Found {0} valid elements (with coordinates) on Overpass.",
            ["PoiSearchService_TroncatoAlTetto"] = "More than {0} elements found: showing the {0} closest to the view center.",
            ["PoiSearchService_TroppiCandidatiAi"] = "Too many candidates for a single AI request ({0}): evaluating only the {1} closest to the view center.",
            ["PoiSearchService_InvioGroq"] = "Sending {0} OSM candidates to Groq/AI to filter and evaluate for \"{1}\"...",
            ["PoiSearchService_RispostaAiRicevuta"] = "AI response received, analyzing the selection...",
            ["PoiSearchService_AiSelezionati"] = "The AI selected {0} relevant places out of {1} candidates.",

            // UI/PoiSearchLogWindow.cs
            ["PoiSearchLogWindow_Titolo"] = "Searching for POIs...",
            ["PoiSearchLogWindow_Annulla"] = "Cancel",
            ["PoiSearchLogWindow_OK"] = "OK",

            // UI/RouteInstradationPanel.cs
            ["RouteInstradationPanel_Titolo"] = "Route \"{0}\"",
            ["RouteInstradationPanel_Profilo"] = "Profile:",
            ["RouteInstradationPanel_ProfiloAuto"] = "Car",
            ["RouteInstradationPanel_ProfiloBici"] = "Bike",
            ["RouteInstradationPanel_ProfiloPiedi"] = "Walk",
            ["RouteInstradationPanel_CreaPercorso"] = "Create route",
            ["RouteInstradationPanel_Totali"] = "Total distance: {0:F1} km — Estimated duration: {1:F0} min",
            ["RouteInstradationPanel_Tratta"] = "Leg {0}: {1:F1} km · {2:F0} min",
            ["RouteInstradationPanel_TrattaFallita"] = "Leg {0}: routing failed",
            ["RouteInstradationPanel_TrattaFallitaConErrore"] = "Leg {0}: routing failed ({1})",
            ["RouteInstradationPanel_TrattaLabel"] = "Leg {0}",
            ["RouteInstradationPanel_AlternativaHeader"] = "Alt. {0}\n{1:F1} km · {2:F0} min",

            // UI/ProgressWindow.cs
            ["ProgressWindow_Avvio"] = "Starting...",

            // UI/PoiGroupEditWindow.cs
            ["PoiGroupEditWindow_TitoloNuovo"] = "New POI group",
            ["PoiGroupEditWindow_TitoloModifica"] = "Edit group  {0}",
            ["PoiGroupEditWindow_Nome"] = "Name:",
            ["PoiGroupEditWindow_Descrizione"] = "Description:",
            ["PoiGroupEditWindow_Colore"] = "Color:",
            ["PoiGroupEditWindow_Icona"] = "Icon:",
            ["PoiGroupEditWindow_Ok"] = "OK",
            ["PoiGroupEditWindow_Annulla"] = "Cancel",
            ["PoiGroupEditWindow_NomeDefault"] = "New group",

            // UI/EditPageWindow.cs
            ["EditPageWindow_Titolo"] = "Edit page  {0}",
            ["EditPageWindow_Etichetta"] = "Label:",
            ["EditPageWindow_Longitudine"] = "Longitude:",
            ["EditPageWindow_Latitudine"] = "Latitude:",
            ["EditPageWindow_Descrizione"] = "Description:",
            ["EditPageWindow_Orientamento"] = "Orientation:",
            ["EditPageWindow_Scala"] = "Scale:",
            ["EditPageWindow_UsaGlobale"] = "(use global settings)",
            ["EditPageWindow_CittaPrincipali"] = "Main cities",
            ["EditPageWindow_CittaPrincipaliTooltip"] =
                "Adds the 3 most populous cities in the area to the description.\n" +
                "Requires cities500.csv in the same folder as the executable.",
            ["EditPageWindow_DatabaseCittaDisponibili"] = "Database: {0} cities available",
            ["EditPageWindow_Ok"] = "OK",
            ["EditPageWindow_Annulla"] = "Cancel",
            ["EditPageWindow_CoordinateValidePrima"] = "Enter valid coordinates first.",
            ["EditPageWindow_NessunaCittaTrovata"] = "No cities found in the area.",
            ["EditPageWindow_CittaTrovate"] = "✅ {0} cities found.",
            ["EditPageWindow_CoordinateNonValide"] = "Invalid coordinates.",

            // UI/PoiItemEditWindow.cs
            ["PoiItemEditWindow_TitoloNuovo"] = "New POI",
            ["PoiItemEditWindow_TitoloModifica"] = "Edit POI  {0}",
            ["PoiItemEditWindow_Etichetta"] = "Label:",
            ["PoiItemEditWindow_Longitudine"] = "Longitude:",
            ["PoiItemEditWindow_Latitudine"] = "Latitude:",
            ["PoiItemEditWindow_Descrizione"] = "Description:",
            ["PoiItemEditWindow_Icona"] = "Icon:",
            ["PoiItemEditWindow_Da"] = "From:",
            ["PoiItemEditWindow_A"] = "To:",
            ["PoiItemEditWindow_DataAFinSenzaDa"] = "\"To\" date set without a \"From\" date.",
            ["PoiItemEditWindow_UsaCentroVistaMappa"] = "Use map view center",
            ["PoiItemEditWindow_CoordinateImpostate"] = "Coordinates set from the map view center.",
            ["PoiItemEditWindow_Ok"] = "OK",
            ["PoiItemEditWindow_Annulla"] = "Cancel",
            ["PoiItemEditWindow_CoordinateNonValide"] = "Invalid coordinates.",
            ["PoiItemEditWindow_LabelDefault"] = "POI",
            ["Gcj_BadgeGcjToWgs"] = "C→W",
            ["Gcj_BadgeWgsToGcj"] = "W→C",
            ["Gcj_TooltipGcjToWgs"] = "Point in China: corrects coordinates from GCJ-02 (Mars, Chinese maps) to real WGS84",
            ["Gcj_TooltipWgsToGcj"] = "Point in China: converts coordinates from WGS84 to GCJ-02 (Mars, for re-exporting to Chinese apps)",
            ["Gcj_PoiCorretto"] = "POI \"{0}\" corrected: from GCJ-02 to WGS84.",
            ["Gcj_PoiConvertito"] = "POI \"{0}\" converted: from WGS84 to GCJ-02.",
            ["Gcj_PuntoPercorsoCorretto"] = "Point {0} of \"{1}\" corrected: from GCJ-02 to WGS84.",
            ["Gcj_PuntoPercorsoConvertito"] = "Point {0} of \"{1}\" converted: from WGS84 to GCJ-02.",
            ["Gcj_ImportCorretti"] = "{0} points corrected from GCJ-02 to WGS84 (China area).",
            ["Gcj_ExportConvertiti"] = "{0} points converted from WGS84 to GCJ-02 (China area).",
            ["Gcj_PuntiInCinaAllApertura"] = "{0} points in the project fall within the China area: check the C→W/W→C icons in the navigation tree.",
            ["Gcj_ChiediCorrezioneImportTitolo"] = "Points in the China area",
            ["Gcj_ChiediCorrezioneImport"] = "The file contains points that fall within China. By specification the KML/GPX format is always WGS84: choose \"Already WGS84\" (default) unless you know for certain the source is a Chinese map app (Amap/Gaode, Baidu...) using GCJ-02 \"Mars\" coordinates — in that case choose \"Apply correction\".",
            ["Gcj_ChiediCorrezioneExportTitolo"] = "Points in the China area",
            ["Gcj_ChiediCorrezioneExport"] = "The project contains points in China. By specification the KML/GPX format is always WGS84: choose \"Keep WGS84\" (default) unless the destination is specifically a Chinese map app (Amap/Gaode, Baidu...) expecting GCJ-02 \"Mars\" coordinates — in that case choose \"Apply conversion\".",
            ["Gcj_ApplicaCorrezione"] = "Apply correction",
            ["Gcj_GiaWgs84"] = "Already WGS84",
            ["Gcj_ApplicaConversione"] = "Apply conversion",
            ["Gcj_LasciaWgs84"] = "Keep WGS84",
            ["Gcj_RilevatoDaNomeFileGcj02"] = "(coordinate system detected from file name: GCJ-02)",
            ["Gcj_RilevatoDaNomeFileWgs84"] = "(coordinate system detected from file name: WGS84)",

            // UI/RouteEditWindow.cs
            ["RouteEditWindow_TitoloNuovo"] = "New route",
            ["RouteEditWindow_TitoloModifica"] = "Edit route  {0}",
            ["RouteEditWindow_Etichetta"] = "Label:",
            ["RouteEditWindow_Descrizione"] = "Description:",
            ["RouteEditWindow_Da"] = "From:",
            ["RouteEditWindow_A"] = "To:",
            ["RouteEditWindow_Colore"] = "Color:",
            ["RouteEditWindow_Ok"] = "OK",
            ["RouteEditWindow_Annulla"] = "Cancel",
            ["RouteEditWindow_PuntiDelPercorso"] = "Route points:",
            ["RouteEditWindow_AggiungiPunto"] = "Add point (map view center)",
            ["RouteEditWindow_NessunPunto"] = "No points. Use \"Add point\" to start (or draw the route on the map).",
            ["RouteEditWindow_PuntiLunghezza"] = "{0} points  ·  length {1} km",
            ["RouteEditWindow_SpostaSu"] = "Move up",
            ["RouteEditWindow_SpostaGiu"] = "Move down",
            ["RouteEditWindow_EliminaPunto"] = "Delete point",
            ["RouteEditWindow_TogglePoi"] = "Mark/unmark as point of interest",
            ["RouteEditWindow_ConservaPoiTitolo"] = "Keep the POI?",
            ["RouteEditWindow_ConservaPoiMessaggio"] = "The point \"{0}\" is also a POI. Do you want to keep it as a standalone POI (in a new group) before removing it from the route?",
            ["RouteEditWindow_ConservaPoiSi"] = "Yes, keep it",
            ["RouteEditWindow_ConservaPoiNo"] = "No, delete it",
            ["RouteEditWindow_PoiLabel"] = "Label:",
            ["RouteEditWindow_PoiDescrizione"] = "Description:",
            ["RouteEditWindow_MinimoDuePunti"] = "The route must have at least 2 points.",
            ["RouteEditWindow_LabelDefault"] = "Route",

            // UI/PoiManagerWindow.cs
            ["PoiManagerWindow_Titolo"] = "Manage points of interest",
            ["PoiManagerWindow_NuovoGruppo"] = "➕ New group",
            ["PoiManagerWindow_ImportaKmz"] = "📂 Import KMZ",
            ["PoiManagerWindow_EsportaKmz"] = "💾 Export KMZ",
            ["PoiManagerWindow_Ok"] = "OK",
            ["PoiManagerWindow_Annulla"] = "Cancel",
            ["PoiManagerWindow_NessunGruppo"] = "No POI groups. Use \"New group\" or \"Import KMZ\" to start.",
            ["PoiManagerWindow_NessunPoiNelGruppo"] = "No POIs in this group.",
            ["PoiManagerWindow_ConteggioPoi"] = "{0} POIs",
            ["PoiManagerWindow_ConteggioPoiConDescrizione"] = "{0} POIs  ·  {1}",
            ["PoiManagerWindow_AggiungiPoiBtn"] = "➕ POI",
            ["PoiManagerWindow_AggiungiPoiTooltip"] = "Add a POI to this group",
            ["PoiManagerWindow_ModificaGruppoTooltip"] = "Edit group",
            ["PoiManagerWindow_EliminaGruppoTooltip"] = "Delete group (and its POIs)",
            ["PoiManagerWindow_ImportaTitolo"] = "Import POIs from KMZ/KML",
            ["PoiManagerWindow_FiltroKmzKml"] = "KMZ/KML",
            ["PoiManagerWindow_FiltroTuttiFile"] = "All files",
            ["PoiManagerWindow_NessunGruppoPoiNelFile"] = "No group/POI found in the file.",
            ["PoiManagerWindow_ImportatiGruppi"] = "Imported {0} groups ({1} POIs).",
            ["PoiManagerWindow_ErroreImportazione"] = "Import error: {0}",
            ["PoiManagerWindow_NessunGruppoDaEsportare"] = "No group to export.",
            ["PoiManagerWindow_EsportaTitolo"] = "Export POIs as KMZ",
            ["PoiManagerWindow_FiltroKmz"] = "KMZ",
            ["PoiManagerWindow_Esportato"] = "Exported: {0}",
            ["PoiManagerWindow_ErroreEsportazione"] = "Export error: {0}",

            // UI/SettingsWindow.cs
            ["SettingsWindow_Titolo"] = "Stradario settings",
            ["SettingsWindow_TabGenerale"] = "General",
            ["SettingsWindow_TabCategoriePoi"] = "POI categories",
            ["SettingsWindow_TabDatiOffline"] = "Offline POI database",
            ["SettingsWindow_Ok"] = "OK",
            ["SettingsWindow_Annulla"] = "Cancel",
            ["SettingsWindow_FormatoPagina"] = "Page size:",
            ["SettingsWindow_Orientamento"] = "Orientation:",
            ["SettingsWindow_Portrait"] = "Portrait",
            ["SettingsWindow_Landscape"] = "Landscape",
            ["SettingsWindow_Dpi"] = "DPI:",
            ["SettingsWindow_Scala"] = "Scale:",
            ["SettingsWindow_BloccoAutomatico"] = "Auto-lock after (seconds, 0=never):",
            ["SettingsWindow_ContrastoMappe"] = "Map contrast (PDF only):",
            ["SettingsWindow_ContrastoNessuno"] = "None",
            ["SettingsWindow_ContrastoColore"] = "Boost color",
            ["SettingsWindow_ContrastoBN"] = "Boost B/W",
            ["SettingsWindow_ContrastoStrade"] = "Emphasize roads",
            ["SettingsWindow_ContrastoAdattivo"] = "Adaptive contrast (local)",
            ["SettingsWindow_RinforzaContorni"] = "Reinforce edges",
            ["SettingsWindow_RinforzaContorniTooltip"] = "Darkens edges (roads, buildings) to make them more legible at high print DPI. Applies on top of whichever mode is selected above.",
            ["SettingsWindow_RetinaturaBN"] = "Dithering for B/W printing",
            ["SettingsWindow_RetinaturaBNTooltip"] = "Converts to pure black/white with a dot pattern (dithering) instead of continuous gray — useful on a monochrome laser printer. Only has an effect with \"Contrasta B/N\".",
            ["SettingsWindow_MappaTileServer"] = "Map (tile server):",
            ["SettingsWindow_ApiKeyTileServer"] = "Tile server API key:",
            ["SettingsWindow_ChiaveTileServerWatermark"] = "Free key from thunderforest.com or stadiamaps.com",
            ["SettingsWindow_InfoTileServer"] = "Coverage: {0}\nCharacteristics: {1}\nRecommended for: {2}",
            ["SettingsWindow_ChiaveGroq"] = "Groq API key (AI place search):",
            ["SettingsWindow_ChiaveGroqWatermark"] = "Optional, from console.groq.com — enables natural-language POI search",
            ["SettingsWindow_IntroCategoriePoi"] =
                "Additional categories for POI search by category, alongside the built-in ones " +
                "(restaurants, pharmacies, etc.). Specify the OSM tag (key and value, e.g. amenity / vending_machine) " +
                "and the label to show in the search menu.",
            ["SettingsWindow_EtichettaWatermark"] = "Label (e.g. water dispensers)",
            ["SettingsWindow_ChiaveOsmWatermark"] = "OSM key (e.g. amenity)",
            ["SettingsWindow_ValoreOsmWatermark"] = "OSM value (e.g. vending_machine)",
            ["SettingsWindow_AggiungiCategoria"] = "➕ Add",
            ["SettingsWindow_CompilaTuttiICampi"] = "Fill in label, key and value before adding.",
            ["SettingsWindow_CategoriaGiaEsistente"] = "A category with the tag \"{0}={1}\" already exists.",
            ["SettingsWindow_NessunaCategoriaPersonalizzata"] = "No custom categories.",
            ["SettingsWindow_CategoriaRiga"] = "{0}  ({1}={2})",
            ["SettingsWindow_RimuoviCategoriaTooltip"] = "Remove this custom category",
            ["SettingsWindow_PreviewPagina"] = "Each page covers about {0} × {1} km",
            ["SettingsWindow_Lingua"] = "Language:",

            // UI/SettingsWindow.cs — "Offline POI database" tab (see
            // Services/PoiOfflineDatabase): one continent at a time, always
            // with all 43 categories together (no partial download).
            ["SettingsWindow_IntroDatiOffline"] =
                "Download OpenStreetMap POI data per continent (generated by osm/OsmExtractor and published on GitHub) " +
                "for instant, offline category searches, without depending on Overpass. Each continent always " +
                "includes all categories together. If a continent isn't downloaded, the search automatically " +
                "falls back to Overpass online.",
            ["SettingsWindow_ControllaAggiornamentiDati"] = "🔄 Check for updates",
            ["SettingsWindow_ControlloAggiornamentiDatiInCorso"] = "Checking the latest version on GitHub...",
            ["SettingsWindow_AttendiDownloadInCorso"] = "⚠ Offline data download/extraction in progress: please wait for it to finish before closing this window.",
            ["SettingsWindow_ControlloAggiornamentiDatiFallito"] = "Update check failed (no network or GitHub unreachable).",
            ["SettingsWindow_UltimaVersioneDatiDisponibile"] = "Latest published data version: {0}",
            ["SettingsWindow_DatiNonScaricati"] = "Not downloaded",
            ["SettingsWindow_DatiVersioneScaricata"] = "Downloaded (version {0})",
            ["SettingsWindow_AggiornamentoDatiDisponibile"] = "Version {0}: update to {1} available",
            ["SettingsWindow_Scarica"] = "⬇ Download",
            ["SettingsWindow_Aggiorna"] = "🔄 Update",
            ["SettingsWindow_Riscarica"] = "⬇ Re-download",
            ["Continent_africa"] = "Africa",
            ["Continent_antarctica"] = "Antarctica",
            ["Continent_asia"] = "Asia",
            ["Continent_australia_oceania"] = "Australia and Oceania",
            ["Continent_central_america"] = "Central America",
            ["Continent_europe"] = "Europe",
            ["Continent_north_america"] = "North America",
            ["Continent_south_america"] = "South America",
            ["SettingsWindow_RiavvioLingua"] = "Restart the app to apply the language change.",

            // UI/MainWindow.cs
            ["MainWindow_Annullato"] = "Undone.",
            ["MainWindow_Ripetuto"] = "Redone.",
            ["MainWindow_SalvataggioAutomatico"] = "Autosave completed.",
            ["MainWindow_ModificheNonSalvateTitolo"] = "Unsaved changes",
            ["MainWindow_ModificheNonSalvateMessaggio"] = "There are unsaved changes.\nDo you want to save before exiting?",
            ["MainWindow_AttendiDownloadInCorso"] = "⚠ Offline data download/extraction in progress: please wait for it to finish before closing the app.",
            ["MainWindow_SalvaEdEsci"] = "💾 Save and exit",
            ["MainWindow_EsciSenzaSalvare"] = "🗑 Exit without saving",
            ["MainWindow_Annulla"] = "Cancel",
            ["MainWindow_SalvaProgettoTitolo"] = "Save stradario project",
            ["MainWindow_FiltroStradario"] = "Stradario",
            ["MainWindow_TitoloApp"] = "Stradario",
            ["MainWindow_SenzaTitolo"] = "Untitled",
            ["MainWindow_StatusBarRiepilogo"] = "{0} pages   ·   {1} POIs ({2} groups)   ·   {3} routes   ·   {4} [{5}]{6}",
            ["MainWindow_Svuota"] = "Clear",
            ["MainWindow_FileRecenti"] = "Recent files",
            ["MainWindow_NuovoProgetto"] = "New project",
            ["MainWindow_ApriProgetto"] = "Open project",
            ["MainWindow_Salva"] = "Save",
            ["MainWindow_SalvaCome"] = "Save as...",
            ["MainWindow_ImportaTooltip"] = "Import POIs/routes from KMZ/KML/GPX",
            ["MainWindow_EsportaTuttoTooltip"] = "Export everything (POIs and routes)",
            ["MainWindow_EsportaTuttoTitolo"] = "Export everything (POIs and routes)",
            ["MainWindow_NienteDaEsportare"] = "Nothing to export: no POI group and no route in the project.",
            ["MainWindow_GeneraPdf"] = "Generate PDF",
            ["MainWindow_AggiornaMappa"] = "Refresh map (clear tile cache)",
            ["MainWindow_AnnullaCtrlZ"] = "Undo (Ctrl+Z)",
            ["MainWindow_RipetiCtrlY"] = "Redo (Ctrl+Y)",
            ["MainWindow_RighelloTooltip"] = "Ruler: measure a distance on the map (click = add point, right click = undo last, ESC = exit)",
            ["MainWindow_CosaCeQuiTooltip"] = "What's here? Click the button then a point on the map (shortcut: shift + right click)",
            ["MainWindow_LocalizzaTooltip"] = "Locate me (centers the map on the current position, updated in real time)",
            ["MainWindow_TestoLiberoWatermark"] = "Free text (optional)",
            ["MainWindow_CercaPoiTooltip"] = "Search for POIs on OpenStreetMap in the visible area",
            ["MainWindow_ImpostazioniTooltip"] = "Settings",
            ["MainWindow_InfoTooltip"] = "About StradarioApp",
            ["MainWindow_NuovaVersioneDisponibile"] = "🔔 New version {0} available — click to download",
            ["MainWindow_ImpostazioniCorrenti"] = "Current settings",
            ["MainWindow_Navigazione"] = "Navigation",
            ["MainWindow_FiltraPerEtichetta"] = "🔎 Filter by label...",
            ["MainWindow_InfoFormato"] = "Size:",
            ["MainWindow_InfoScala"] = "Scale:",
            ["MainWindow_InfoCopertura"] = "Coverage:",
            ["MainWindow_AggiungiPaginaTooltip"] = "Add page (click on the map)",
            ["MainWindow_EliminaPagineSelezionateTooltip"] = "Delete the {0} selected pages (Ctrl+click to select more than one)",
            ["MainWindow_NascondiPagineTooltip"] = "Hide pages on the map",
            ["MainWindow_MostraPagineTooltip"] = "Show pages on the map",
            ["MainWindow_SbloccaTuttePagineTooltip"] = "Unlock all pages",
            ["MainWindow_BloccaTuttePagineTooltip"] = "Lock all pages",
            ["MainWindow_Pagine"] = "Pages",
            ["MainWindow_NessunaPaginaFiltro"] = "No page matches the filter.",
            ["MainWindow_NessunaPaginaVuota"] = "No pages. Use \"➕\" to add one.",
            ["MainWindow_EsportaGruppiPoiTooltip"] = "Export all POI groups (KMZ/KML/GPX)",
            ["MainWindow_EsportaGruppoTooltip"] = "Export this group (KMZ/KML/GPX)",
            ["MainWindow_NuovoGruppoPoiTooltip"] = "New POI group",
            ["MainWindow_TagliaPoiTooltip"] = "Cut (to move it to another group)",
            ["MainWindow_AnnullaTaglioPoiTooltip"] = "Cancel cut",
            ["MainWindow_IncollaPoiTooltip"] = "Paste the {0} cut POIs here",
            ["MainWindow_TagliaPuntoPercorsoTooltip"] = "Cut (to move it to another route)",
            ["MainWindow_AnnullaTaglioPuntoPercorsoTooltip"] = "Cancel cut",
            ["MainWindow_IncollaPuntiPercorsoTooltip"] = "Paste the {0} cut points here",
            ["MainWindow_NascondiPoiTooltip"] = "Hide all POIs on the map",
            ["MainWindow_MostraPoiTooltip"] = "Show all POIs on the map",
            ["MainWindow_SbloccaGruppiPoiTooltip"] = "Unlock all POI groups",
            ["MainWindow_BloccaGruppiPoiTooltip"] = "Lock all POI groups",
            ["MainWindow_GruppiPoi"] = "POI groups",
            ["MainWindow_NessunGruppoPoiFiltro"] = "No group/POI matches the filter.",
            ["MainWindow_NessunGruppoPoiVuoto"] = "No groups. Use \"➕\" or import a KMZ.",
            ["MainWindow_NessunPoiNelGruppo"] = "No POIs in this group.",
            ["MainWindow_EsportaPercorsiTooltip"] = "Export all routes (KMZ/KML/GPX)",
            ["MainWindow_EsportaPercorsoTooltip"] = "Export this route (KMZ/KML/GPX)",
            ["MainWindow_NuovoPercorsoTooltip"] = "New route (draw on the map)",
            ["MainWindow_NascondiPercorsiTooltip"] = "Hide all routes on the map",
            ["MainWindow_MostraPercorsiTooltip"] = "Show all routes on the map",
            ["MainWindow_SbloccaPercorsiTooltip"] = "Unlock all routes",
            ["MainWindow_BloccaPercorsiTooltip"] = "Lock all routes",
            ["MainWindow_Percorsi"] = "Routes",
            ["MainWindow_NessunPercorsoFiltro"] = "No route matches the filter.",
            ["MainWindow_NessunPercorsoVuoto"] = "No routes. Use \"➕\" to draw one on the map, or import a KMZ.",
            ["MainWindow_AggiungiPoiAlGruppoTooltip"] = "Add POI to this group (click on the map)",
            ["MainWindow_ModificaGruppoTooltip"] = "Edit group",
            ["MainWindow_EliminaGruppoTooltip"] = "Delete group (and its POIs)",
            ["MainWindow_NascondiGruppoTooltip"] = "Hide this group on the map",
            ["MainWindow_MostraGruppoTooltip"] = "Show this group on the map",
            ["MainWindow_SbloccaGruppoTooltip"] = "Unlock group (allow dragging POIs again)",
            ["MainWindow_BloccaGruppoTooltip"] = "Lock group (prevent accidental dragging of POIs)",
            ["MainWindow_ModificaPoiTooltip"] = "Edit POI",
            ["MainWindow_EliminaPoiTooltip"] = "Delete POI",
            ["MainWindow_AggiungiPuntiPercorsoTooltip"] = "Add points to this route (click on the map)",
            ["MainWindow_InstradaTooltip"] = "Route on roads (OSRM)",
            ["MainWindow_InstradaFallitoTooltip"] = "Routing failed for at least one leg — try again",
            ["MainWindow_InstradaMaxPunti"] = "Routing is only possible up to 10 points: reduce the route's points before trying again.",
            ["MainWindow_ModificaPercorsoTooltip"] = "Edit route",
            ["MainWindow_PuntoPercorsoNumero"] = "Point {0}",
            ["MainWindow_EliminaPercorsoTooltip"] = "Delete route",
            ["MainWindow_NascondiPercorsoTooltip"] = "Hide this route on the map",
            ["MainWindow_MostraPercorsoTooltip"] = "Show this route on the map",
            ["MainWindow_SbloccaPercorsoTooltip"] = "Unlock route (allow dragging points again)",
            ["MainWindow_BloccaPercorsoTooltip"] = "Lock route (prevent accidental dragging of points)",
            ["MainWindow_ModificaEtichettaDescrizioneTooltip"] = "Edit label and description",
            ["MainWindow_EliminaPaginaTooltip"] = "Delete page",
            ["MainWindow_SbloccaPaginaTooltip"] = "Unlock page (allow dragging again)",
            ["MainWindow_BloccaPaginaTooltip"] = "Lock page (prevent accidental dragging)",
            ["MainWindow_OverlayAggiungiPagina"] = "Click on the map to place the page  (right click = cancel)",
            ["MainWindow_OverlayDisegnaPercorso"] = "Click to add points to the route  (shift+click = finish, right click = undo last point, ESC = cancel)",
            ["MainWindow_OverlayAggiungiPoi"] = "Click on the map to place the new POI  (right click = cancel)",
            ["MainWindow_OverlayEstendiPercorso"] = "Click to extend the route  (shift+click = finish, right click = undo last point, ESC = cancel)",
            ["MainWindow_OverlayInstrada"] = "Click a dashed alternative to select it  (right click/ESC = cancel)",
            ["MainWindow_OverlayIdentifica"] = "Click on the map to see what's there  (right click/ESC = cancel)",
            ["MainWindow_OverlayRighelloInizio"] = "Ruler: click to start measuring  (right click = cancel, ESC = exit)",
            ["MainWindow_OverlayRighelloProsegui"] = "Ruler: {0} of {1} points  —  click to continue (right click = undo last, ESC = exit)",
            ["MainWindow_OverlayRisultatiRicerca"] = "{0} results: click a marker to add it (ESC = cancel)",
            ["MainWindow_OverlayAreaTroppoAmpia"] = " — area too wide: results only around the map center",
            ["MainWindow_PercorsoMinimoDuePuntiAnnullato"] = "The route must have at least 2 points. Drawing canceled.",
            ["MainWindow_LocalizzazioneAvvio"] = "Locating: starting the location service…",
            ["MainWindow_LocalizzazioneServizioAvviato"] = "Locating: system service started, waiting for position…",
            ["MainWindow_LocalizzazioneRiuscita"] = "Location successful: position found.",
            ["MainWindow_LocalizzazioneFallita"] = "Location failed: {0}",
            ["MainWindow_RicercaLabelDefault"] = "Search",
            ["MainWindow_PiuGruppiPoiAperti"] = "More than one POI group is expanded in the tree: collapse all but the one you want the result added to.",
            ["MainWindow_IndirizzoWatermark"] = "Address: street, city... (required)",
            ["MainWindow_CittaWatermark"] = "City name, even partial (empty = visible ones)",
            ["MainWindow_LogAvvioRicerca"] = "Starting search \"{0}\"",
            ["MainWindow_LogConTesto"] = " with text \"{0}\"",
            ["MainWindow_LogGeocodificaLuogo"] = "Place detected in the text: geocoding \"{0}\"...",
            ["MainWindow_CercoSullaMappa"] = "Searching for \"{0}\" on the map…",
            ["MainWindow_LogGeocodificaFallita"] = "Geocoding failed: {0}",
            ["MainWindow_LogLuogoTrovato"] = "Place found: recentering the search there.",
            ["MainWindow_LuogoNonTrovato"] = "Place \"{0}\" not found: searching for \"{1}\" in the name, in the visible area.",
            ["MainWindow_LogRicercaAnnullataUtente"] = "Search canceled by the user.",
            ["MainWindow_RicercaAnnullata"] = "Search canceled.",
            ["MainWindow_LogAreaTroppoAmpiaRestringo"] = "Visible area too wide ({0}° x {1}°): restricting the search to {2}°x{3}° around the map center.",
            ["MainWindow_LabelConTestoTraVirgolette"] = "{0} \"{1}\"",
            ["MainWindow_AreaTroppoAmpiaCercoIntorno"] = "Area too wide: searching for {0} only around the map center...",
            ["MainWindow_CercoNellaZona"] = "Searching for {0} in the area...",
            ["MainWindow_LogCercoCategoriaArea"] = "Searching for \"{0}\" ({1}={2}) in the area...",
            ["MainWindow_ErroreRicercaCategoria"] = "Category search error (Overpass): {0}",
            ["MainWindow_LogProvoDatabaseOffline"] = "Trying the offline POI database first...",
            ["MainWindow_LogTrovatiOffline"] = "{0} results found in the offline database: using these (no request sent to Overpass).",
            ["MainWindow_SuggerimentoDatiOfflineNonScaricati"] = "No offline POI database downloaded: the search will use Overpass online (Settings → Offline POI database to download the data).",
            ["MainWindow_LogPunteggioLocale"] = "Computing local score (name/tags) for \"{0}\"...",
            ["MainWindow_SelezioneAiNonRiuscita"] = "AI selection failed: {0}",
            ["MainWindow_LogSaltoAttesaAi"] = "AI wait interrupted by the user: showing results found so far (local score).",
            ["MainWindow_TooltipAffidabilita"] = "Confidence: {0}%",
            ["MainWindow_LogNessunRisultatoPer"] = "No results for \"{0}\".",
            ["MainWindow_NessunRisultatoAreaRistretta"] = "No results for \"{0}\" around the map center (area too wide, search restricted): try moving/zooming the view.",
            ["MainWindow_NessunRisultatoZonaVisualizzata"] = "No results for \"{0}\" in the visible area.",
            ["MainWindow_LogRisultatiTrovatiMostro"] = "{0} results found: showing them on the map.",
            ["MainWindow_ResRisultatiPer"] = "{0} results for \"{1}\"",
            ["MainWindow_ResSelezionatiAI"] = " (selected by AI)",
            ["MainWindow_ResClickMarker"] = ": click the markers on the map to add them, one or more (ESC = exit).",
            ["MainWindow_ResPossiblyTruncated"] = " (there could be more: try narrowing the area)",
            ["MainWindow_ResAreaClamped"] = " (visible area too wide: only results around the center are shown)",
            ["MainWindow_ScriviIndirizzoPrimaCercare"] = "Write an address (street, city) in the text field before searching.",
            ["MainWindow_LogCercoIndirizzo"] = "Searching for the address \"{0}\"...",
            ["MainWindow_ErroreRicercaIndirizzo"] = "Address search error: {0}",
            ["MainWindow_NessunIndirizzoTrovatoPer"] = "No address found for \"{0}\".",
            ["MainWindow_LogIndirizziTrovatiMostro"] = "{0} addresses found: showing them on the map.",
            ["MainWindow_RisultatiPerIndirizzo"] = "{0} results for the address \"{1}\": click the markers on the map to add them, one or more (ESC = exit).",
            ["MainWindow_LogNessunNomeCercoPopolose"] = "No name entered: searching for the most populous cities in the visible area...",
            ["MainWindow_CercoCittaVisibili"] = "Searching for visible cities in the area...",
            ["MainWindow_NessunaCittaTrovataArea"] = "No cities found in the visible area ({0}).",
            ["MainWindow_Popolazione"] = "Population: {0}",
            ["MainWindow_CategoriaCitta"] = "city",
            ["MainWindow_LogCercoCittaContiene"] = "Searching for cities whose name contains \"{0}\" in cities500.csv...",
            ["MainWindow_CercoCitta"] = "Searching for city \"{0}\"...",
            ["MainWindow_NessunaCittaTrovataPer"] = "No cities found for \"{0}\" ({1} cities in the visible map).",
            ["MainWindow_LogCittaTrovateMostro"] = "{0} cities found: showing them on the map.",
            ["MainWindow_CittaNellAreaVisualizzata"] = "cities in the visible area",
            ["MainWindow_CittaTraVirgolette"] = "city \"{0}\"",
            ["MainWindow_CittaNellAreaVisualizzataConteggio"] = "{0} cities in the visible area",
            ["MainWindow_CittaTrovatePerConteggio"] = "{0} cities found for \"{1}\"",
            ["MainWindow_ClicMarkerAggiungerli"] = ": click the markers on the map to add them, one or more (ESC = exit).",
            ["MainWindow_RicercaCosaSiTrova"] = "Searching for what's at this point...",
            ["MainWindow_NessunaInfoTrovataPunto"] = "No information found for this point.",
            ["MainWindow_RicercaGps"] = "GPS search",
            ["MainWindow_TrovatoClicMarker"] = "Found: {0}. Click the marker to add it (ESC = exit).",
            ["MainWindow_ErroreRicercaInversa"] = "Reverse search error: {0}",
            ["MainWindow_NessunFileRecente"] = "No recent files",
            ["MainWindow_EliminaPagineTitolo"] = "Delete pages",
            ["MainWindow_EliminarePagineSelezionate"] = "Delete the {0} selected pages?",
            ["MainWindow_EliminatePagine"] = "Deleted {0} pages.",
            ["MainWindow_Si"] = "Yes",
            ["MainWindow_SpostatiPoiNelGruppo"] = "Moved {0} POIs to group \"{1}\".",
            ["MainWindow_SpostatiPuntiNelPercorso"] = "Moved {0} points to route \"{1}\".",
            ["MainWindow_PoiPercorsoConservato"] = "POI \"{0}\" kept in new group \"{1}\".",
            ["MainWindow_SpostatiPuntiNelPercorsoConScarti"] = "Moved {0} points to route \"{1}\" ({2} not moved: a route needs at least 2 points).",
            ["MainWindow_NuovoStradarioProjectName"] = "New Stradario",
            ["MainWindow_ApriProgettoTitolo"] = "Open stradario project",
            ["MainWindow_FiltroTuttiFile"] = "All files",
            ["MainWindow_ErroreAperturaFile"] = "Error opening file:\n{0}",
            ["MainWindow_ErroreSalvataggio"] = "Save error:\n{0}",
            ["MainWindow_ProgettoHaModifiche"] = "The project has unsaved changes.\nDo you want to save it before continuing?",
            ["MainWindow_SalvaEmoji"] = "💾 Save",
            ["MainWindow_ScartaEmoji"] = "🗑 Discard",
            ["MainWindow_NessunaPaginaDefinita"] = "No pages defined. Add at least one page before generating the PDF.",
            ["MainWindow_GenerazionePdfInCorso"] = "Generating PDF...",
            ["MainWindow_ErroreGenerazionePdf"] = "PDF generation error:\n{0}",
            ["MainWindow_AnteprimaPdfTitolo"] = "PDF preview",
            ["MainWindow_PdfGeneratoMessaggio"] = "The PDF has been generated and opened in the system viewer for preview.\nDo you want to save it to a permanent location?",
            ["MainWindow_ChiudiEmoji"] = "✕ Close",
            ["MainWindow_SalvaPdfTitolo"] = "Save stradario PDF",
            ["MainWindow_FiltroPdf"] = "PDF",
            ["MainWindow_PdfSalvato"] = "PDF saved: {0}",
            ["MainWindow_PoiLabelDefault"] = "POI",
            ["MainWindow_AggiuntoAlGruppo"] = "Added \"{0}\" to group \"{1}\".",
            ["MainWindow_AltriRisultatiSullaMappa"] = " {0} more results on the map: keep clicking them, ESC to exit.",
            ["MainWindow_NessunGruppoDaEsportare"] = "No group to export.",
            ["MainWindow_EsportaPoiTitolo"] = "Export POIs",
            ["MainWindow_FiltroKmzIcone"] = "KMZ (zip, with icons)",
            ["MainWindow_FiltroKml"] = "KML",
            ["MainWindow_FiltroGpx"] = "GPX",
            ["MainWindow_FiltroCsv"] = "CSV",
            ["MainWindow_Esportato"] = "Exported: {0}",
            ["MainWindow_ErroreEsportazione"] = "Export error:\n{0}",
            ["MainWindow_FileVuotoDiagnostica"] =
                "The selected file appears empty (0 bytes read) even after several attempts.\n" +
                "Diagnostics — Name: \"{0}\", TryGetLocalPath: \"{1}\", " +
                "stream.CanSeek: {2}, stream.Length: {3}, " +
                "FileInfo.Length on local path: {4}.",
            ["MainWindow_ImportaPoiPercorsiTitolo"] = "Import POIs and/or routes from KMZ/KML/GPX",
            ["MainWindow_FiltroKmzKmlGpx"] = "KMZ/KML/GPX/CSV",
            ["MainWindow_CsvNonRiconosciuto"] = "Unrecognized CSV: missing the columns of a StradarioApp POI export (Gruppo/Nome/Lat/Lon) or Routes export (Percorso/IndicePunto/Lat/Lon).",
            ["MainWindow_NessunGruppoPercorsoTrovato"] = "No POI group or route found in the file.",
            ["MainWindow_ImportatiGruppiPoiConteggio"] = "{0} POI groups ({1} POIs)",
            ["MainWindow_ImportatiPercorsiConteggio"] = "{0} routes",
            ["MainWindow_ImportatiRiepilogo"] = "Imported: {0}.",
            ["MainWindow_ImportatiPiuFile"] = "Imported {0} files.",
            ["MainWindow_ErroreImportazioneDi"] = "Error importing \"{0}\":\n{1}",
            ["MainWindow_NessunPercorsoDaEsportare"] = "No route to export.",
            ["MainWindow_EsportaPercorsiTitolo"] = "Export routes",
            ["MainWindow_FiltroKmzZip"] = "KMZ (zip)",
            ["MainWindow_Ok"] = "OK",
            ["MainWindow_TitoloConProgetto"] = "Stradario - {0} [{1}]{2}",
            ["MainWindow_ErroreTitolo"] = "Error",

            ["AboutWindow_Titolo"] = "About StradarioApp",
            ["AboutWindow_Descrizione"] = "Builds street atlases (page-based road maps) from OpenStreetMap tiles: pages, points of interest and routes, exported to a print-ready PDF.",
            ["AboutWindow_Versione"] = "Version {0}",
            ["AboutWindow_ControllaAggiornamenti"] = "Check for updates",
            ["AboutWindow_ControlloInCorso"] = "Checking...",
            ["AboutWindow_NessunAggiornamento"] = "You already have the latest version.",
            ["AboutWindow_NuovaVersioneTrovata"] = "Version {0} is available.",
            ["AboutWindow_ControlloFallito"] = "Check failed (verify your Internet connection).",
            ["AboutWindow_ApriPagina"] = "Open release page",
            ["AboutWindow_RepositoryGitHub"] = "GitHub repository",
            ["AboutWindow_Licenza"] = "GNU GPL v3.0 license",
            ["AboutWindow_DatiMappe"] = "Map data © OpenStreetMap contributors",
            ["AboutWindow_Chiudi"] = "Close",
        };
    }
}
