// =============================================================================
// Resources/ItStrings.cs
//
// SINOSSI: Dizionario centralizzato di tutte le stringhe italiane visibili
//   all'utente (titoli finestre, testi bottoni/label/tooltip, messaggi di
//   stato/errore/conferma). Fase 1 dell'internazionalizzazione: estrae il
//   testo letterale finora sparso nei file UI/*.cs in un unico posto, senza
//   cambiare nulla di quello che l'utente vede oggi. Convenzione chiavi:
//   <NomeClasseSenzaEstensione>_<DescrizioneBreveInPascalCase>. Le stringhe
//   con placeholder posizionali (usate con string.Format) mantengono il
//   segnaposto {0}, {1}, ... nell'ordine esatto in cui compaiono nel codice
//   originale.
// =============================================================================

using System.Collections.Generic;

namespace StradarioApp.Resources
{
    internal static class ItStrings
    {
        public static readonly Dictionary<string, string> Map = new()
        {
            // Services/PoiSearchService.cs — etichette del combo categoria
            // POI (built-in, vedi Categories/AllCategories/LocalizedCategoryLabel).
            // Chiave = "PoiCategory_<tag OSM key>_<tag OSM value>", o
            // "PoiCategory___special___address"/"..._city" per le due voci
            // sentinella in testa al combo. Le categorie personalizzate
            // aggiunte dall'utente (Impostazioni) NON hanno una voce qui:
            // restano nella lingua in cui l'utente le ha scritte.
            ["PoiCategory___special___address"] = "Ricerca un indirizzo",
            ["PoiCategory___special___city"] = "Ricerca una città (anche parziale)",
            ["PoiCategory_railway_station"] = "stazioni ferroviarie",
            ["PoiCategory_station_subway"] = "stazioni della metropolitana",
            ["PoiCategory_amenity_pharmacy"] = "farmacie",
            ["PoiCategory_amenity_restaurant"] = "ristoranti",
            ["PoiCategory_amenity_bar"] = "bar",
            ["PoiCategory_amenity_cafe"] = "caffetterie",
            ["PoiCategory_amenity_parking"] = "parcheggi",
            ["PoiCategory_amenity_hospital"] = "ospedali",
            ["PoiCategory_amenity_school"] = "scuole",
            ["PoiCategory_tourism_hotel"] = "hotel",
            ["PoiCategory_shop_supermarket"] = "supermercati",
            ["PoiCategory_shop_butcher"] = "macellerie",
            ["PoiCategory_shop_bakery"] = "panetterie",
            ["PoiCategory_amenity_bank"] = "banche",
            ["PoiCategory_amenity_atm"] = "bancomat",
            ["PoiCategory_amenity_place_of_worship"] = "luoghi di culto",
            ["PoiCategory_tourism_museum"] = "musei",
            ["PoiCategory_aeroway_aerodrome"] = "aeroporti",
            ["PoiCategory_highway_bus_stop"] = "fermate bus",
            ["PoiCategory_amenity_toilets"] = "servizi igienici",
            ["PoiCategory_amenity_fuel"] = "distributori di benzina",
            ["PoiCategory_amenity_post_office"] = "uffici postali",
            ["PoiCategory_amenity_library"] = "biblioteche",
            ["PoiCategory_amenity_cinema"] = "cinema",
            ["PoiCategory_amenity_vending_machine"] = "distributori automatici",
            ["PoiCategory_shop_newsagent"] = "edicole",
            ["PoiCategory_amenity_fast_food"] = "fast food",
            ["PoiCategory_shop_tobacco"] = "tabaccherie",
            ["PoiCategory_shop_hairdresser"] = "parrucchieri",
            ["PoiCategory_amenity_veterinary"] = "veterinari",
            ["PoiCategory_amenity_charging_station"] = "colonnine ricarica elettrica",
            ["PoiCategory_amenity_drinking_water"] = "fontanelle (acqua potabile)",
            ["PoiCategory_shop_laundry"] = "lavanderie",
            ["PoiCategory_amenity_taxi"] = "posteggi taxi",
            ["PoiCategory_amenity_bus_station"] = "capolinea bus",
            ["PoiCategory_aeroway_terminal"] = "terminal aeroportuali",
            ["PoiCategory_tourism_attraction"] = "attrazioni turistiche",
            ["PoiCategory_tourism_viewpoint"] = "punti panoramici",
            ["PoiCategory_historic_monument"] = "monumenti",
            ["PoiCategory_amenity_bicycle_rental"] = "noleggio bici",
            ["PoiCategory_amenity_bicycle_parking"] = "parcheggi bici",
            ["PoiCategory_tourism_information"] = "uffici turistici",
            ["PoiCategory_amenity_bureau_de_change"] = "uffici cambio",

            // Services/PoiSearchService.cs (righe di log passate a onProgress,
            // mostrate in UI/PoiSearchLogWindow)
            ["PoiSearchService_AttendoNominatim"] = "Attendo il turno per interrogare Nominatim (max 1 richiesta/secondo)...",
            ["PoiSearchService_InterrogoNominatimLuogo"] = "Interrogo Nominatim per il luogo \"{0}\"...",
            ["PoiSearchService_NominatimNessunLuogo"] = "Nominatim non ha trovato nessun luogo per \"{0}\".",
            ["PoiSearchService_InterrogoNominatimIndirizzo"] = "Interrogo Nominatim per l'indirizzo \"{0}\"...",
            ["PoiSearchService_IndirizziTrovati"] = "Trovati {0} indirizzi corrispondenti.",
            ["PoiSearchService_TrovataInCache"] = "Trovata in cache la stessa ricerca ({0}={1}) per quest'area: nessuna nuova richiesta a Overpass.",
            ["PoiSearchService_QueryOverpassCostruita"] = "Costruita la query Overpass per \"{0}={1}\" nell'area {2},{3} – {4},{5}.",
            ["PoiSearchService_InvioRichiestaOverpass"] = "Invio la richiesta al server pubblico Overpass (overpass-api.de)...",
            ["PoiSearchService_RispostaOverpassRicevuta"] = "Risposta ricevuta da Overpass, analizzo gli elementi trovati...",
            ["PoiSearchService_ElementiValidiTrovati"] = "Trovati {0} elementi validi (con coordinate) su Overpass.",
            ["PoiSearchService_TroncatoAlTetto"] = "Più di {0} elementi trovati: mostro i {0} più vicini al centro della vista.",
            ["PoiSearchService_TroppiCandidatiAi"] = "Troppi candidati per una singola richiesta AI ({0}): ne valuto solo i {1} più vicini al centro della vista.",
            ["PoiSearchService_InvioGroq"] = "Invio a Groq/AI {0} candidati OSM da filtrare e valutare per \"{1}\"...",
            ["PoiSearchService_RispostaAiRicevuta"] = "Risposta AI ricevuta, analizzo la selezione...",
            ["PoiSearchService_AiSelezionati"] = "L'AI ha selezionato {0} luoghi pertinenti su {1} candidati.",

            // UI/PoiSearchLogWindow.cs
            ["PoiSearchLogWindow_Titolo"] = "Ricerca POI in corso...",
            ["PoiSearchLogWindow_Annulla"] = "Annulla",

            // UI/RouteInstradationPanel.cs
            ["RouteInstradationPanel_Titolo"] = "Instrada \"{0}\"",
            ["RouteInstradationPanel_Profilo"] = "Profilo:",
            ["RouteInstradationPanel_ProfiloAuto"] = "Auto",
            ["RouteInstradationPanel_ProfiloBici"] = "Bici",
            ["RouteInstradationPanel_ProfiloPiedi"] = "Piedi",
            ["RouteInstradationPanel_CreaPercorso"] = "Crea percorso",
            ["RouteInstradationPanel_Totali"] = "Distanza totale: {0:F1} km — Durata stimata: {1:F0} min",
            ["RouteInstradationPanel_Tratta"] = "Tratta {0}: {1:F1} km · {2:F0} min",
            ["RouteInstradationPanel_TrattaFallita"] = "Tratta {0}: instradamento fallito",
            ["RouteInstradationPanel_TrattaFallitaConErrore"] = "Tratta {0}: instradamento fallito ({1})",

            // UI/ProgressWindow.cs
            ["ProgressWindow_Avvio"] = "Avvio...",

            // UI/PoiGroupEditWindow.cs
            ["PoiGroupEditWindow_TitoloNuovo"] = "Nuovo gruppo POI",
            ["PoiGroupEditWindow_TitoloModifica"] = "Modifica gruppo  {0}",
            ["PoiGroupEditWindow_Nome"] = "Nome:",
            ["PoiGroupEditWindow_Descrizione"] = "Descrizione:",
            ["PoiGroupEditWindow_Colore"] = "Colore:",
            ["PoiGroupEditWindow_Icona"] = "Icona:",
            ["PoiGroupEditWindow_Ok"] = "OK",
            ["PoiGroupEditWindow_Annulla"] = "Annulla",
            ["PoiGroupEditWindow_NomeDefault"] = "Nuovo gruppo",

            // UI/EditPageWindow.cs
            ["EditPageWindow_Titolo"] = "Modifica pagina  {0}",
            ["EditPageWindow_Etichetta"] = "Etichetta:",
            ["EditPageWindow_Longitudine"] = "Longitudine:",
            ["EditPageWindow_Latitudine"] = "Latitudine:",
            ["EditPageWindow_Descrizione"] = "Descrizione:",
            ["EditPageWindow_CittaPrincipali"] = "Città principali",
            ["EditPageWindow_CittaPrincipaliTooltip"] =
                "Inserisce nella descrizione le 3 città più popolose nell'area.\n" +
                "Richiede cities500.csv nella stessa cartella dell'eseguibile.",
            ["EditPageWindow_DatabaseCittaDisponibili"] = "Database: {0} città disponibili",
            ["EditPageWindow_Ok"] = "OK",
            ["EditPageWindow_Annulla"] = "Annulla",
            ["EditPageWindow_CoordinateValidePrima"] = "Inserisci coordinate valide prima.",
            ["EditPageWindow_NessunaCittaTrovata"] = "Nessuna città trovata nell'area.",
            ["EditPageWindow_CittaTrovate"] = "✅ {0} città trovate.",
            ["EditPageWindow_CoordinateNonValide"] = "Coordinate non valide.",

            // UI/PoiItemEditWindow.cs
            ["PoiItemEditWindow_TitoloNuovo"] = "Nuovo POI",
            ["PoiItemEditWindow_TitoloModifica"] = "Modifica POI  {0}",
            ["PoiItemEditWindow_Etichetta"] = "Etichetta:",
            ["PoiItemEditWindow_Longitudine"] = "Longitudine:",
            ["PoiItemEditWindow_Latitudine"] = "Latitudine:",
            ["PoiItemEditWindow_Descrizione"] = "Descrizione:",
            ["PoiItemEditWindow_UsaCentroVistaMappa"] = "Usa centro vista mappa",
            ["PoiItemEditWindow_CoordinateImpostate"] = "Coordinate impostate dal centro della vista mappa.",
            ["PoiItemEditWindow_Ok"] = "OK",
            ["PoiItemEditWindow_Annulla"] = "Annulla",
            ["PoiItemEditWindow_CoordinateNonValide"] = "Coordinate non valide.",
            ["PoiItemEditWindow_LabelDefault"] = "POI",
            ["Gcj_BadgeGcjToWgs"] = "C→W",
            ["Gcj_BadgeWgsToGcj"] = "W→C",
            ["Gcj_TooltipGcjToWgs"] = "Punto in Cina: corregge le coordinate da GCJ-02 (Mars, mappe cinesi) a WGS84 reale",
            ["Gcj_TooltipWgsToGcj"] = "Punto in Cina: converte le coordinate da WGS84 a GCJ-02 (Mars, per riesportare verso app cinesi)",
            ["Gcj_PoiCorretto"] = "POI \"{0}\" corretto: da GCJ-02 a WGS84.",
            ["Gcj_PoiConvertito"] = "POI \"{0}\" convertito: da WGS84 a GCJ-02.",
            ["Gcj_PuntoPercorsoCorretto"] = "Punto {0} di \"{1}\" corretto: da GCJ-02 a WGS84.",
            ["Gcj_PuntoPercorsoConvertito"] = "Punto {0} di \"{1}\" convertito: da WGS84 a GCJ-02.",
            ["Gcj_ImportCorretti"] = "{0} punti corretti da GCJ-02 a WGS84 (area Cina).",
            ["Gcj_ExportConvertiti"] = "{0} punti convertiti da WGS84 a GCJ-02 (area Cina).",
            ["Gcj_PuntiInCinaAllApertura"] = "{0} punti del progetto ricadono in area Cina: verifica le icone C→W/W→C nell'albero di navigazione.",
            ["Gcj_ChiediCorrezioneImportTitolo"] = "Punti in area Cina",
            ["Gcj_ChiediCorrezioneImport"] = "Il file contiene punti che ricadono in Cina. Per specifica il formato KML/GPX è sempre in WGS84: scegli \"Sono già WGS84\" (default) a meno che tu non sappia con certezza che la fonte è un'app di mappe cinese (Amap/Gaode, Baidu...) che usa coordinate GCJ-02 \"Mars\" — in quel caso scegli \"Applica correzione\".",
            ["Gcj_ChiediCorrezioneExportTitolo"] = "Punti in area Cina",
            ["Gcj_ChiediCorrezioneExport"] = "Il progetto contiene punti in Cina. Per specifica il formato KML/GPX è sempre in WGS84: scegli \"Lascia WGS84\" (default) a meno che la destinazione non sia specificamente un'app di mappe cinese (Amap/Gaode, Baidu...) che si aspetta coordinate GCJ-02 \"Mars\" — in quel caso scegli \"Applica conversione\".",
            ["Gcj_ApplicaCorrezione"] = "Applica correzione",
            ["Gcj_GiaWgs84"] = "Sono già WGS84",
            ["Gcj_ApplicaConversione"] = "Applica conversione",
            ["Gcj_LasciaWgs84"] = "Lascia WGS84",
            ["Gcj_RilevatoDaNomeFileGcj02"] = "(sistema di coordinate rilevato dal nome file: GCJ-02)",
            ["Gcj_RilevatoDaNomeFileWgs84"] = "(sistema di coordinate rilevato dal nome file: WGS84)",

            // UI/RouteEditWindow.cs
            ["RouteEditWindow_TitoloNuovo"] = "Nuovo percorso",
            ["RouteEditWindow_TitoloModifica"] = "Modifica percorso  {0}",
            ["RouteEditWindow_Etichetta"] = "Etichetta:",
            ["RouteEditWindow_Descrizione"] = "Descrizione:",
            ["RouteEditWindow_Colore"] = "Colore:",
            ["RouteEditWindow_Ok"] = "OK",
            ["RouteEditWindow_Annulla"] = "Annulla",
            ["RouteEditWindow_PuntiDelPercorso"] = "Punti del percorso:",
            ["RouteEditWindow_AggiungiPunto"] = "Aggiungi punto (centro vista mappa)",
            ["RouteEditWindow_NessunPunto"] = "Nessun punto. Usa \"Aggiungi punto\" per iniziare (oppure disegna il percorso sulla mappa).",
            ["RouteEditWindow_PuntiLunghezza"] = "{0} punti  ·  lunghezza {1} km",
            ["RouteEditWindow_SpostaSu"] = "Sposta su",
            ["RouteEditWindow_SpostaGiu"] = "Sposta giù",
            ["RouteEditWindow_EliminaPunto"] = "Elimina punto",
            ["RouteEditWindow_MinimoDuePunti"] = "Il percorso deve avere almeno 2 punti.",
            ["RouteEditWindow_LabelDefault"] = "Percorso",

            // UI/PoiManagerWindow.cs
            ["PoiManagerWindow_Titolo"] = "Gestione punti di interesse",
            ["PoiManagerWindow_NuovoGruppo"] = "➕ Nuovo gruppo",
            ["PoiManagerWindow_ImportaKmz"] = "📂 Importa KMZ",
            ["PoiManagerWindow_EsportaKmz"] = "💾 Esporta KMZ",
            ["PoiManagerWindow_Ok"] = "OK",
            ["PoiManagerWindow_Annulla"] = "Annulla",
            ["PoiManagerWindow_NessunGruppo"] = "Nessun gruppo di POI. Usa \"Nuovo gruppo\" o \"Importa KMZ\" per iniziare.",
            ["PoiManagerWindow_NessunPoiNelGruppo"] = "Nessun POI in questo gruppo.",
            ["PoiManagerWindow_ConteggioPoi"] = "{0} POI",
            ["PoiManagerWindow_ConteggioPoiConDescrizione"] = "{0} POI  ·  {1}",
            ["PoiManagerWindow_AggiungiPoiBtn"] = "➕ POI",
            ["PoiManagerWindow_AggiungiPoiTooltip"] = "Aggiungi un POI a questo gruppo",
            ["PoiManagerWindow_ModificaGruppoTooltip"] = "Modifica gruppo",
            ["PoiManagerWindow_EliminaGruppoTooltip"] = "Elimina gruppo (e i suoi POI)",
            ["PoiManagerWindow_ImportaTitolo"] = "Importa POI da KMZ/KML",
            ["PoiManagerWindow_FiltroKmzKml"] = "KMZ/KML",
            ["PoiManagerWindow_FiltroTuttiFile"] = "Tutti i file",
            ["PoiManagerWindow_NessunGruppoPoiNelFile"] = "Nessun gruppo/POI trovato nel file.",
            ["PoiManagerWindow_ImportatiGruppi"] = "Importati {0} gruppi ({1} POI).",
            ["PoiManagerWindow_ErroreImportazione"] = "Errore importazione: {0}",
            ["PoiManagerWindow_NessunGruppoDaEsportare"] = "Nessun gruppo da esportare.",
            ["PoiManagerWindow_EsportaTitolo"] = "Esporta POI come KMZ",
            ["PoiManagerWindow_FiltroKmz"] = "KMZ",
            ["PoiManagerWindow_Esportato"] = "Esportato: {0}",
            ["PoiManagerWindow_ErroreEsportazione"] = "Errore esportazione: {0}",

            // UI/SettingsWindow.cs
            ["SettingsWindow_Titolo"] = "Impostazioni stradario",
            ["SettingsWindow_TabGenerale"] = "Generale",
            ["SettingsWindow_TabCategoriePoi"] = "Categorie POI",
            ["SettingsWindow_TabDatiOffline"] = "Database POI offline",
            ["SettingsWindow_Ok"] = "OK",
            ["SettingsWindow_Annulla"] = "Annulla",
            ["SettingsWindow_FormatoPagina"] = "Formato pagina:",
            ["SettingsWindow_Orientamento"] = "Orientamento:",
            ["SettingsWindow_Portrait"] = "Portrait",
            ["SettingsWindow_Landscape"] = "Landscape",
            ["SettingsWindow_Dpi"] = "DPI:",
            ["SettingsWindow_Scala"] = "Scala:",
            ["SettingsWindow_BloccoAutomatico"] = "Blocco automatico dopo (secondi, 0=mai):",
            ["SettingsWindow_ContrastoMappe"] = "Contrasto mappe (solo PDF):",
            ["SettingsWindow_ContrastoNessuno"] = "Nessuno",
            ["SettingsWindow_ContrastoColore"] = "Contrasta colore",
            ["SettingsWindow_ContrastoBN"] = "Contrasta B/N",
            ["SettingsWindow_ContrastoStrade"] = "Enfatizza strade",
            ["SettingsWindow_MappaTileServer"] = "Mappa (tile server):",
            ["SettingsWindow_ApiKeyTileServer"] = "API key tile server:",
            ["SettingsWindow_ChiaveTileServerWatermark"] = "Chiave gratuita da thunderforest.com o stadiamaps.com",
            ["SettingsWindow_InfoTileServer"] = "Copertura: {0}\nCaratteristiche: {1}\nConsigliato per: {2}",
            ["SettingsWindow_ChiaveGroq"] = "Chiave API Groq (ricerca luoghi AI):",
            ["SettingsWindow_ChiaveGroqWatermark"] = "Facoltativa, da console.groq.com — abilita la ricerca POI in linguaggio naturale",
            ["SettingsWindow_IntroCategoriePoi"] =
                "Categorie aggiuntive per la ricerca POI per categoria, oltre a quelle predefinite " +
                "(ristoranti, farmacie, ecc.). Specifica il tag OSM (chiave e valore, es. amenity / vending_machine) " +
                "e l'etichetta da mostrare nel menu di ricerca.",
            ["SettingsWindow_EtichettaWatermark"] = "Etichetta (es. distributori acqua)",
            ["SettingsWindow_ChiaveOsmWatermark"] = "Chiave OSM (es. amenity)",
            ["SettingsWindow_ValoreOsmWatermark"] = "Valore OSM (es. vending_machine)",
            ["SettingsWindow_AggiungiCategoria"] = "➕ Aggiungi",
            ["SettingsWindow_CompilaTuttiICampi"] = "Compila etichetta, chiave e valore prima di aggiungere.",
            ["SettingsWindow_CategoriaGiaEsistente"] = "Esiste già una categoria con il tag \"{0}={1}\".",
            ["SettingsWindow_NessunaCategoriaPersonalizzata"] = "Nessuna categoria personalizzata.",
            ["SettingsWindow_CategoriaRiga"] = "{0}  ({1}={2})",
            ["SettingsWindow_RimuoviCategoriaTooltip"] = "Rimuovi questa categoria personalizzata",
            ["SettingsWindow_PreviewPagina"] = "Ogni pagina copre circa {0} × {1} km",
            ["SettingsWindow_Lingua"] = "Lingua:",

            // UI/SettingsWindow.cs — tab "Database POI offline" (vedi
            // Services/PoiOfflineDatabase): un continente alla volta, sempre
            // con tutte le 43 categorie insieme (nessun download parziale).
            ["SettingsWindow_IntroDatiOffline"] =
                "Scarica i dati POI OpenStreetMap per continente (generati da osm/OsmExtractor e pubblicati su GitHub) " +
                "per avere ricerche per categoria istantanee e offline, senza dipendere da Overpass. Ogni continente " +
                "include sempre tutte le categorie insieme. Se un continente non è scaricato, la ricerca ripiega " +
                "automaticamente su Overpass online.",
            ["SettingsWindow_ControllaAggiornamentiDati"] = "🔄 Controlla aggiornamenti",
            ["SettingsWindow_ControlloAggiornamentiDatiInCorso"] = "Controllo la versione più recente su GitHub...",
            ["SettingsWindow_AttendiDownloadInCorso"] = "⚠ Download/estrazione dati offline in corso: attendi il completamento prima di chiudere questa finestra.",
            ["SettingsWindow_ControlloAggiornamentiDatiFallito"] = "Controllo aggiornamenti non riuscito (rete assente o GitHub non raggiungibile).",
            ["SettingsWindow_UltimaVersioneDatiDisponibile"] = "Ultima versione dati pubblicata: {0}",
            ["SettingsWindow_DatiNonScaricati"] = "Non scaricato",
            ["SettingsWindow_DatiVersioneScaricata"] = "Scaricato (versione {0})",
            ["SettingsWindow_AggiornamentoDatiDisponibile"] = "Versione {0}: disponibile aggiornamento a {1}",
            ["SettingsWindow_Scarica"] = "⬇ Scarica",
            ["SettingsWindow_Aggiorna"] = "🔄 Aggiorna",
            ["SettingsWindow_Riscarica"] = "⬇ Riscarica",
            ["Continent_africa"] = "Africa",
            ["Continent_antarctica"] = "Antartide",
            ["Continent_asia"] = "Asia",
            ["Continent_australia_oceania"] = "Australia e Oceania",
            ["Continent_central_america"] = "America Centrale",
            ["Continent_europe"] = "Europa",
            ["Continent_north_america"] = "Nord America",
            ["Continent_south_america"] = "Sud America",
            ["SettingsWindow_RiavvioLingua"] = "Riavvia l'app per applicare il cambio di lingua.",

            // UI/MainWindow.cs
            ["MainWindow_Annullato"] = "Annullato.",
            ["MainWindow_Ripetuto"] = "Ripetuto.",
            ["MainWindow_SalvataggioAutomatico"] = "Salvataggio automatico effettuato.",
            ["MainWindow_ModificheNonSalvateTitolo"] = "Modifiche non salvate",
            ["MainWindow_ModificheNonSalvateMessaggio"] = "Ci sono modifiche non salvate.\nVuoi salvare prima di uscire?",
            ["MainWindow_AttendiDownloadInCorso"] = "⚠ Download/estrazione dati offline in corso: attendi il completamento prima di chiudere il programma.",
            ["MainWindow_SalvaEdEsci"] = "💾 Salva ed esci",
            ["MainWindow_EsciSenzaSalvare"] = "🗑 Esci senza salvare",
            ["MainWindow_Annulla"] = "Annulla",
            ["MainWindow_SalvaProgettoTitolo"] = "Salva progetto stradario",
            ["MainWindow_FiltroStradario"] = "Stradario",
            ["MainWindow_TitoloApp"] = "Stradario",
            ["MainWindow_SenzaTitolo"] = "Senza titolo",
            ["MainWindow_StatusBarRiepilogo"] = "{0} pagine   ·   {1} POI ({2} gruppi)   ·   {3} percorsi   ·   {4} [{5}]{6}",
            ["MainWindow_Svuota"] = "Svuota",
            ["MainWindow_FileRecenti"] = "File recenti",
            ["MainWindow_NuovoProgetto"] = "Nuovo progetto",
            ["MainWindow_ApriProgetto"] = "Apri progetto",
            ["MainWindow_Salva"] = "Salva",
            ["MainWindow_SalvaCome"] = "Salva come...",
            ["MainWindow_ImportaTooltip"] = "Importa POI/percorsi da KMZ/KML/GPX",
            ["MainWindow_EsportaTuttoTooltip"] = "Esporta tutto (POI e percorsi)",
            ["MainWindow_EsportaTuttoTitolo"] = "Esporta tutto (POI e percorsi)",
            ["MainWindow_NienteDaEsportare"] = "Niente da esportare: nessun gruppo POI e nessun percorso nel progetto.",
            ["MainWindow_GeneraPdf"] = "Genera PDF",
            ["MainWindow_AggiornaMappa"] = "Aggiorna mappa (svuota cache tile)",
            ["MainWindow_AnnullaCtrlZ"] = "Annulla (Ctrl+Z)",
            ["MainWindow_RipetiCtrlY"] = "Ripeti (Ctrl+Y)",
            ["MainWindow_RighelloTooltip"] = "Righello: misura una distanza sulla mappa (clic = aggiungi punto, tasto destro = annulla ultimo, ESC = esci)",
            ["MainWindow_CosaCeQuiTooltip"] = "Cosa c'è qui? Clicca il bottone poi un punto sulla mappa (scorciatoia: shift + tasto destro)",
            ["MainWindow_LocalizzaTooltip"] = "Localizza dove sono (centra la mappa sulla posizione attuale, aggiornata in tempo reale)",
            ["MainWindow_TestoLiberoWatermark"] = "Testo libero (opzionale)",
            ["MainWindow_CercaPoiTooltip"] = "Cerca POI su OpenStreetMap nell'area visualizzata",
            ["MainWindow_ImpostazioniTooltip"] = "Impostazioni",
            ["MainWindow_InfoTooltip"] = "Informazioni su StradarioApp",
            ["MainWindow_NuovaVersioneDisponibile"] = "🔔 Nuova versione {0} disponibile — clicca per scaricarla",
            ["MainWindow_ImpostazioniCorrenti"] = "Impostazioni correnti",
            ["MainWindow_Navigazione"] = "Navigazione",
            ["MainWindow_FiltraPerEtichetta"] = "🔎 Filtra per etichetta...",
            ["MainWindow_InfoFormato"] = "Formato:",
            ["MainWindow_InfoScala"] = "Scala:",
            ["MainWindow_InfoCopertura"] = "Copertura:",
            ["MainWindow_AggiungiPaginaTooltip"] = "Aggiungi pagina (clic sulla mappa)",
            ["MainWindow_EliminaPagineSelezionateTooltip"] = "Elimina le {0} pagine selezionate (Ctrl+clic per selezionarne più di una)",
            ["MainWindow_NascondiPagineTooltip"] = "Nascondi le pagine sulla mappa",
            ["MainWindow_MostraPagineTooltip"] = "Mostra le pagine sulla mappa",
            ["MainWindow_SbloccaTuttePagineTooltip"] = "Sblocca tutte le pagine",
            ["MainWindow_BloccaTuttePagineTooltip"] = "Blocca tutte le pagine",
            ["MainWindow_Pagine"] = "Pagine",
            ["MainWindow_NessunaPaginaFiltro"] = "Nessuna pagina corrisponde al filtro.",
            ["MainWindow_NessunaPaginaVuota"] = "Nessuna pagina. Usa \"➕\" per aggiungerne una.",
            ["MainWindow_EsportaGruppiPoiTooltip"] = "Esporta tutti i gruppi POI (KMZ/KML/GPX)",
            ["MainWindow_EsportaGruppoTooltip"] = "Esporta questo gruppo (KMZ/KML/GPX)",
            ["MainWindow_NuovoGruppoPoiTooltip"] = "Nuovo gruppo POI",
            ["MainWindow_TagliaPoiTooltip"] = "Taglia (per spostarlo in un altro gruppo)",
            ["MainWindow_AnnullaTaglioPoiTooltip"] = "Annulla il taglio",
            ["MainWindow_IncollaPoiTooltip"] = "Incolla qui i {0} POI tagliati",
            ["MainWindow_NascondiPoiTooltip"] = "Nascondi tutti i POI sulla mappa",
            ["MainWindow_MostraPoiTooltip"] = "Mostra tutti i POI sulla mappa",
            ["MainWindow_SbloccaGruppiPoiTooltip"] = "Sblocca tutti i gruppi POI",
            ["MainWindow_BloccaGruppiPoiTooltip"] = "Blocca tutti i gruppi POI",
            ["MainWindow_GruppiPoi"] = "Gruppi POI",
            ["MainWindow_NessunGruppoPoiFiltro"] = "Nessun gruppo/POI corrisponde al filtro.",
            ["MainWindow_NessunGruppoPoiVuoto"] = "Nessun gruppo. Usa \"➕\" o importa un KMZ.",
            ["MainWindow_NessunPoiNelGruppo"] = "Nessun POI in questo gruppo.",
            ["MainWindow_EsportaPercorsiTooltip"] = "Esporta tutti i percorsi (KMZ/KML/GPX)",
            ["MainWindow_EsportaPercorsoTooltip"] = "Esporta questo percorso (KMZ/KML/GPX)",
            ["MainWindow_NuovoPercorsoTooltip"] = "Nuovo percorso (disegna sulla mappa)",
            ["MainWindow_NascondiPercorsiTooltip"] = "Nascondi tutti i percorsi sulla mappa",
            ["MainWindow_MostraPercorsiTooltip"] = "Mostra tutti i percorsi sulla mappa",
            ["MainWindow_SbloccaPercorsiTooltip"] = "Sblocca tutti i percorsi",
            ["MainWindow_BloccaPercorsiTooltip"] = "Blocca tutti i percorsi",
            ["MainWindow_Percorsi"] = "Percorsi",
            ["MainWindow_NessunPercorsoFiltro"] = "Nessun percorso corrisponde al filtro.",
            ["MainWindow_NessunPercorsoVuoto"] = "Nessun percorso. Usa \"➕\" per disegnarne uno sulla mappa, o importa un KMZ.",
            ["MainWindow_AggiungiPoiAlGruppoTooltip"] = "Aggiungi POI a questo gruppo (clic sulla mappa)",
            ["MainWindow_ModificaGruppoTooltip"] = "Modifica gruppo",
            ["MainWindow_EliminaGruppoTooltip"] = "Elimina gruppo (e i suoi POI)",
            ["MainWindow_NascondiGruppoTooltip"] = "Nascondi questo gruppo sulla mappa",
            ["MainWindow_MostraGruppoTooltip"] = "Mostra questo gruppo sulla mappa",
            ["MainWindow_SbloccaGruppoTooltip"] = "Sblocca gruppo (permetti di nuovo il trascinamento dei POI)",
            ["MainWindow_BloccaGruppoTooltip"] = "Blocca gruppo (impedisci il trascinamento accidentale dei POI)",
            ["MainWindow_ModificaPoiTooltip"] = "Modifica POI",
            ["MainWindow_EliminaPoiTooltip"] = "Elimina POI",
            ["MainWindow_AggiungiPuntiPercorsoTooltip"] = "Aggiungi punti a questo percorso (clic sulla mappa)",
            ["MainWindow_InstradaTooltip"] = "Instrada su strada (OSRM)",
            ["MainWindow_InstradaFallitoTooltip"] = "Instradamento fallito per almeno una tratta — riprova",
            ["MainWindow_InstradaMaxPunti"] = "Instradamento possibile solo fino a 5 punti: riduci i punti del percorso prima di riprovare.",
            ["MainWindow_ModificaPercorsoTooltip"] = "Modifica percorso",
            ["MainWindow_PuntoPercorsoNumero"] = "Punto {0}",
            ["MainWindow_EliminaPercorsoTooltip"] = "Elimina percorso",
            ["MainWindow_NascondiPercorsoTooltip"] = "Nascondi questo percorso sulla mappa",
            ["MainWindow_MostraPercorsoTooltip"] = "Mostra questo percorso sulla mappa",
            ["MainWindow_SbloccaPercorsoTooltip"] = "Sblocca percorso (permetti di nuovo il trascinamento dei punti)",
            ["MainWindow_BloccaPercorsoTooltip"] = "Blocca percorso (impedisci il trascinamento accidentale dei punti)",
            ["MainWindow_ModificaEtichettaDescrizioneTooltip"] = "Modifica etichetta e descrizione",
            ["MainWindow_EliminaPaginaTooltip"] = "Elimina pagina",
            ["MainWindow_SbloccaPaginaTooltip"] = "Sblocca pagina (permetti di nuovo il trascinamento)",
            ["MainWindow_BloccaPaginaTooltip"] = "Blocca pagina (impedisci il trascinamento accidentale)",
            ["MainWindow_OverlayAggiungiPagina"] = "Clicca sulla mappa per posizionare la pagina  (tasto destro = annulla)",
            ["MainWindow_OverlayDisegnaPercorso"] = "Clicca per aggiungere punti al percorso  (shift+clic = fine, tasto destro = annulla ultimo punto, ESC = annulla)",
            ["MainWindow_OverlayAggiungiPoi"] = "Clicca sulla mappa per posizionare il nuovo POI  (tasto destro = annulla)",
            ["MainWindow_OverlayEstendiPercorso"] = "Clicca per estendere il percorso  (shift+clic = fine, tasto destro = annulla ultimo punto, ESC = annulla)",
            ["MainWindow_OverlayInstrada"] = "Clicca su un'alternativa tratteggiata per selezionarla  (tasto destro/ESC = annulla)",
            ["MainWindow_OverlayIdentifica"] = "Clicca sulla mappa per vedere cosa c'è in quel punto  (tasto destro/ESC = annulla)",
            ["MainWindow_OverlayRighelloInizio"] = "Righello: clicca per iniziare a misurare  (tasto destro = annulla, ESC = esci)",
            ["MainWindow_OverlayRighelloProsegui"] = "Righello: {0} su {1} punti  —  clicca per continuare (tasto destro = annulla ultimo, ESC = esci)",
            ["MainWindow_OverlayRisultatiRicerca"] = "{0} risultati: clicca un marker per aggiungerlo (ESC = annulla)",
            ["MainWindow_OverlayAreaTroppoAmpia"] = " — area troppo ampia: risultati solo intorno al centro della mappa",
            ["MainWindow_PercorsoMinimoDuePuntiAnnullato"] = "Il percorso deve avere almeno 2 punti. Disegno annullato.",
            ["MainWindow_LocalizzazioneAvvio"] = "Localizzazione: avvio il servizio di posizione…",
            ["MainWindow_LocalizzazioneServizioAvviato"] = "Localizzazione: servizio di sistema avviato, attendo la posizione…",
            ["MainWindow_LocalizzazioneRiuscita"] = "Localizzazione riuscita: posizione trovata.",
            ["MainWindow_LocalizzazioneFallita"] = "Localizzazione non riuscita: {0}",
            ["MainWindow_RicercaLabelDefault"] = "Ricerca",
            ["MainWindow_PiuGruppiPoiAperti"] = "Più di un gruppo POI è aperto nell'albero: chiudi tutti tranne quello in cui vuoi aggiungere il risultato.",
            ["MainWindow_IndirizzoWatermark"] = "Indirizzo: via, città... (obbligatorio)",
            ["MainWindow_CittaWatermark"] = "Nome città, anche parziale (vuoto = quelle visibili)",
            ["MainWindow_LogAvvioRicerca"] = "Avvio ricerca \"{0}\"",
            ["MainWindow_LogConTesto"] = " con testo \"{0}\"",
            ["MainWindow_LogGeocodificaLuogo"] = "Rilevato un luogo nel testo: geocodifico \"{0}\"...",
            ["MainWindow_CercoSullaMappa"] = "Cerco \"{0}\" sulla mappa…",
            ["MainWindow_LogGeocodificaFallita"] = "Geocodifica fallita: {0}",
            ["MainWindow_LogLuogoTrovato"] = "Luogo trovato: ricentro la ricerca lì.",
            ["MainWindow_LuogoNonTrovato"] = "Luogo \"{0}\" non trovato: cerco \"{1}\" nel nome, nell'area visualizzata.",
            ["MainWindow_LogRicercaAnnullataUtente"] = "Ricerca annullata dall'utente.",
            ["MainWindow_RicercaAnnullata"] = "Ricerca annullata.",
            ["MainWindow_LogAreaTroppoAmpiaRestringo"] = "Area visualizzata troppo ampia ({0}° x {1}°): restringo la ricerca a {2}°x{3}° intorno al centro della mappa.",
            ["MainWindow_LabelConTestoTraVirgolette"] = "{0} \"{1}\"",
            ["MainWindow_AreaTroppoAmpiaCercoIntorno"] = "Area troppo ampia: cerco {0} solo intorno al centro della mappa...",
            ["MainWindow_CercoNellaZona"] = "Cerco {0} nella zona...",
            ["MainWindow_LogCercoCategoriaArea"] = "Cerco \"{0}\" ({1}={2}) nell'area...",
            ["MainWindow_ErroreRicercaCategoria"] = "Errore ricerca per categoria (Overpass): {0}",
            ["MainWindow_LogProvoDatabaseOffline"] = "Provo prima il database POI offline...",
            ["MainWindow_LogTrovatiOffline"] = "{0} risultati trovati nel database offline: uso questi (nessuna richiesta a Overpass).",
            ["MainWindow_SuggerimentoDatiOfflineNonScaricati"] = "Nessun database POI offline scaricato: la ricerca userà Overpass online (Impostazioni → Database POI offline per scaricare i dati).",
            ["MainWindow_LogPunteggioLocale"] = "Calcolo il punteggio locale (nome/tag) per \"{0}\"...",
            ["MainWindow_SelezioneAiNonRiuscita"] = "Selezione AI non riuscita: {0}",
            ["MainWindow_TooltipAffidabilita"] = "Affidabilità: {0}%",
            ["MainWindow_LogNessunRisultatoPer"] = "Nessun risultato per \"{0}\".",
            ["MainWindow_NessunRisultatoAreaRistretta"] = "Nessun risultato per \"{0}\" intorno al centro della mappa (area troppo ampia, ricerca ristretta): prova a spostare/zoomare la vista.",
            ["MainWindow_NessunRisultatoZonaVisualizzata"] = "Nessun risultato per \"{0}\" nella zona visualizzata.",
            ["MainWindow_LogRisultatiTrovatiMostro"] = "{0} risultati trovati: li mostro sulla mappa.",
            ["MainWindow_ResRisultatiPer"] = "{0} risultati per \"{1}\"",
            ["MainWindow_ResSelezionatiAI"] = " (selezionati dall'AI)",
            ["MainWindow_ResClickMarker"] = ": clicca i marker sulla mappa per aggiungerli, uno o più di uno (ESC = esci).",
            ["MainWindow_ResPossiblyTruncated"] = " (potrebbero essercene altri: prova a restringere l'area)",
            ["MainWindow_ResAreaClamped"] = " (area visualizzata troppo ampia: mostrati solo i risultati intorno al centro)",
            ["MainWindow_ScriviIndirizzoPrimaCercare"] = "Scrivi un indirizzo (via, città) nel campo di testo prima di cercare.",
            ["MainWindow_LogCercoIndirizzo"] = "Cerco l'indirizzo \"{0}\"...",
            ["MainWindow_ErroreRicercaIndirizzo"] = "Errore ricerca indirizzo: {0}",
            ["MainWindow_NessunIndirizzoTrovatoPer"] = "Nessun indirizzo trovato per \"{0}\".",
            ["MainWindow_LogIndirizziTrovatiMostro"] = "{0} indirizzi trovati: li mostro sulla mappa.",
            ["MainWindow_RisultatiPerIndirizzo"] = "{0} risultati per l'indirizzo \"{1}\": clicca i marker sulla mappa per aggiungerli, uno o più di uno (ESC = esci).",
            ["MainWindow_LogNessunNomeCercoPopolose"] = "Nessun nome digitato: cerco le città più popolose nell'area visualizzata...",
            ["MainWindow_CercoCittaVisibili"] = "Cerco le città visibili nell'area...",
            ["MainWindow_NessunaCittaTrovataArea"] = "Nessuna città trovata nell'area visualizzata ({0}).",
            ["MainWindow_Popolazione"] = "Popolazione: {0}",
            ["MainWindow_CategoriaCitta"] = "città",
            ["MainWindow_LogCercoCittaContiene"] = "Cerco città il cui nome contiene \"{0}\" in cities500.csv...",
            ["MainWindow_CercoCitta"] = "Cerco città \"{0}\"...",
            ["MainWindow_NessunaCittaTrovataPer"] = "Nessuna città trovata per \"{0}\" ({1} città nella mappa visualizzata).",
            ["MainWindow_LogCittaTrovateMostro"] = "{0} città trovate: le mostro sulla mappa.",
            ["MainWindow_CittaNellAreaVisualizzata"] = "città nell'area visualizzata",
            ["MainWindow_CittaTraVirgolette"] = "città \"{0}\"",
            ["MainWindow_CittaNellAreaVisualizzataConteggio"] = "{0} città nell'area visualizzata",
            ["MainWindow_CittaTrovatePerConteggio"] = "{0} città trovate per \"{1}\"",
            ["MainWindow_ClicMarkerAggiungerli"] = ": clicca i marker sulla mappa per aggiungerli, uno o più di uno (ESC = esci).",
            ["MainWindow_RicercaCosaSiTrova"] = "Ricerca di cosa si trova in questo punto...",
            ["MainWindow_NessunaInfoTrovataPunto"] = "Nessuna informazione trovata per questo punto.",
            ["MainWindow_RicercaGps"] = "Ricerca GPS",
            ["MainWindow_TrovatoClicMarker"] = "Trovato: {0}. Clicca il marker per aggiungerlo (ESC = esci).",
            ["MainWindow_ErroreRicercaInversa"] = "Errore ricerca inversa: {0}",
            ["MainWindow_NessunFileRecente"] = "Nessun file recente",
            ["MainWindow_EliminaPagineTitolo"] = "Elimina pagine",
            ["MainWindow_EliminarePagineSelezionate"] = "Eliminare le {0} pagine selezionate?",
            ["MainWindow_EliminatePagine"] = "Eliminate {0} pagine.",
            ["MainWindow_Si"] = "Sì",
            ["MainWindow_SpostatiPoiNelGruppo"] = "Spostati {0} POI nel gruppo \"{1}\".",
            ["MainWindow_NuovoStradarioProjectName"] = "Nuovo Stradario",
            ["MainWindow_ApriProgettoTitolo"] = "Apri progetto stradario",
            ["MainWindow_FiltroTuttiFile"] = "Tutti i file",
            ["MainWindow_ErroreAperturaFile"] = "Errore apertura file:\n{0}",
            ["MainWindow_ErroreSalvataggio"] = "Errore salvataggio:\n{0}",
            ["MainWindow_ProgettoHaModifiche"] = "Il progetto ha modifiche non salvate.\nVuoi salvarlo prima di continuare?",
            ["MainWindow_SalvaEmoji"] = "💾 Salva",
            ["MainWindow_ScartaEmoji"] = "🗑 Scarta",
            ["MainWindow_NessunaPaginaDefinita"] = "Nessuna pagina definita. Aggiungi almeno una pagina prima di generare il PDF.",
            ["MainWindow_GenerazionePdfInCorso"] = "Generazione PDF in corso...",
            ["MainWindow_ErroreGenerazionePdf"] = "Errore generazione PDF:\n{0}",
            ["MainWindow_AnteprimaPdfTitolo"] = "Anteprima PDF",
            ["MainWindow_PdfGeneratoMessaggio"] = "Il PDF è stato generato e aperto nel visualizzatore di sistema per l'anteprima.\nVuoi salvarlo in una posizione definitiva?",
            ["MainWindow_ChiudiEmoji"] = "✕ Chiudi",
            ["MainWindow_SalvaPdfTitolo"] = "Salva PDF stradario",
            ["MainWindow_FiltroPdf"] = "PDF",
            ["MainWindow_PdfSalvato"] = "PDF salvato: {0}",
            ["MainWindow_PoiLabelDefault"] = "POI",
            ["MainWindow_AggiuntoAlGruppo"] = "Aggiunto \"{0}\" al gruppo \"{1}\".",
            ["MainWindow_AltriRisultatiSullaMappa"] = " Altri {0} risultati sulla mappa: continua a cliccarli, ESC per uscire.",
            ["MainWindow_NessunGruppoDaEsportare"] = "Nessun gruppo da esportare.",
            ["MainWindow_EsportaPoiTitolo"] = "Esporta POI",
            ["MainWindow_FiltroKmzIcone"] = "KMZ (zip, con icone)",
            ["MainWindow_FiltroKml"] = "KML",
            ["MainWindow_FiltroGpx"] = "GPX",
            ["MainWindow_Esportato"] = "Esportato: {0}",
            ["MainWindow_ErroreEsportazione"] = "Errore esportazione:\n{0}",
            ["MainWindow_FileVuotoDiagnostica"] =
                "Il file selezionato risulta vuoto (0 byte letti) anche dopo alcuni tentativi.\n" +
                "Diagnostica — Name: \"{0}\", TryGetLocalPath: \"{1}\", " +
                "stream.CanSeek: {2}, stream.Length: {3}, " +
                "FileInfo.Length su path locale: {4}.",
            ["MainWindow_ImportaPoiPercorsiTitolo"] = "Importa POI e/o percorsi da KMZ/KML/GPX",
            ["MainWindow_FiltroKmzKmlGpx"] = "KMZ/KML/GPX",
            ["MainWindow_NessunGruppoPercorsoTrovato"] = "Nessun gruppo POI o percorso trovato nel file.",
            ["MainWindow_ImportatiGruppiPoiConteggio"] = "{0} gruppi POI ({1} POI)",
            ["MainWindow_ImportatiPercorsiConteggio"] = "{0} percorsi",
            ["MainWindow_ImportatiRiepilogo"] = "Importati: {0}.",
            ["MainWindow_ErroreImportazioneDi"] = "Errore importazione di \"{0}\":\n{1}",
            ["MainWindow_NessunPercorsoDaEsportare"] = "Nessun percorso da esportare.",
            ["MainWindow_EsportaPercorsiTitolo"] = "Esporta percorsi",
            ["MainWindow_FiltroKmzZip"] = "KMZ (zip)",
            ["MainWindow_Ok"] = "OK",
            ["MainWindow_TitoloConProgetto"] = "Stradario - {0} [{1}]{2}",
            ["MainWindow_ErroreTitolo"] = "Errore",

            ["AboutWindow_Titolo"] = "Informazioni su StradarioApp",
            ["AboutWindow_Descrizione"] = "Crea stradari (atlanti stradali a pagine) da mappe OpenStreetMap: pagine, punti di interesse e percorsi, esportati in un PDF pronto per la stampa.",
            ["AboutWindow_Versione"] = "Versione {0}",
            ["AboutWindow_ControllaAggiornamenti"] = "Controlla aggiornamenti",
            ["AboutWindow_ControlloInCorso"] = "Controllo in corso...",
            ["AboutWindow_NessunAggiornamento"] = "Hai già la versione più recente.",
            ["AboutWindow_NuovaVersioneTrovata"] = "È disponibile la versione {0}.",
            ["AboutWindow_ControlloFallito"] = "Controllo non riuscito (verifica la connessione a Internet).",
            ["AboutWindow_ApriPagina"] = "Apri pagina della release",
            ["AboutWindow_RepositoryGitHub"] = "Repository su GitHub",
            ["AboutWindow_Licenza"] = "Licenza GNU GPL v3.0",
            ["AboutWindow_DatiMappe"] = "Dati cartografici © contributori OpenStreetMap",
            ["AboutWindow_Chiudi"] = "Chiudi",
        };
    }
}
